/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gravix } from "./Gravix";
export * as factories from "./factories";
export { Gravix__factory } from "./factories/Gravix__factory";
