/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gravix } from './Gravix.js'
export * as factories from './factories/index.js'
export { Gravix__factory } from './factories/Gravix__factory.js'
